[project]
name = "diffbot-analytics"
version = "0.1.0"
description = "Conversational Analytics Dashboard powered by Diffbot LLM"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.28.0",
    "openai>=1.3.0",
    "python-dotenv>=1.0.0",
    "pandas>=2.0.0",
    "plotly>=5.15.0",
]